### ISSUE TITLE
padding/margin somewhat off

### ISSUE THREAD

**Issue by fxfactorial** [theslip/react-bootstrap-intl-tel-input#8]
I got this on the iPhone 6/7 simulator on current latest chrome:

<img width="352" alt="screen shot 2018-04-18 at 6 37 39 pm" src="https://user-images.githubusercontent.com/3036816/38966566-c07e7cb2-4337-11e8-8b57-4efda59ad5c0.png">

**Comment by theslip** [comment]
What version of bootstrap are you using? This package was developed on 4.0.0-alpha.6, so I'm not sure if it will appear correctly on newer versions.
